### ISSUE TITLE
Atomic testing list screen is still very slow

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1177] opened 2024-07-01 20:52 UTC
## Description

Atomic testing list screen is still very slow

https://testing.obas.staging.filigran.io/admin/atomic_testings
https://demo.obas.filigran.io/admin/atomic_testings

**Comment by jborozco** [comment] 2024-07-02 16:25
Duplicate of https://github.com/OpenBAS-Platform/openbas/issues/1184

**Closed by jborozco** 2024-07-02 16:25 UTC
Labels: bug, needs triage
