### ISSUE TITLE
Pagination elements number do not change when searching

### ISSUE THREAD

**Issue by guillaumejparis** [OpenBAS-Platform/openbas#1846] opened 2024-11-12 16:25 UTC
![Image](https://github.com/user-attachments/assets/e0934e65-5d3f-4693-b732-03dc1a7338bf)

**Comment by EllynBsc** [comment] 2024-11-12 16:38
Hi @guillaumejparis,

I'm not sure here if I understand the problem well. What should be the expected output ?

**Comment by guillaumejparis** [comment] 2024-11-12 16:41
If I use a filter that will give me no result the pagination number change : 
![Image](https://github.com/user-attachments/assets/eeada0f5-aff3-4b07-967e-a8780faf2fbf)

**Comment by guillaumejparis** [comment] 2024-11-12 16:41
It seems that when searching we do not update the number of elements in the pagination

**Comment by EllynBsc** [comment] 2024-12-30 14:52
This is a duplicate of #1677

**Closed by EllynBsc** 2024-12-30 14:52 UTC
Labels: bug, duplicate
