### ISSUE TITLE
Team score over time in % of expectations is not correctly computed

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1045] opened 2024-06-02 05:00 UTC
## Description

The score cannot decrease over time:

![image](https://github.com/OpenBAS-Platform/openbas/assets/1334279/8d9808cd-3d20-4098-a012-72cb020d490f)

**Comment by savacano28** [comment] 2024-06-24 06:29
Hi! Could I get the URL for this example? I think this error might have been fixed by https://github.com/OpenBAS-Platform/openbas/pull/1108 (duplication of expectations)

**Comment by jborozco** [comment] 2024-06-27 07:18
I can't reproduce the error anymore, it seem to have been fixed. Closing the issue.

**Closed by jborozco** 2024-06-27 07:18 UTC
Labels: bug
