### ISSUE TITLE
Fields not displayed correctly when editing a simulation

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1635] opened 2024-10-11 15:46 UTC
## Description

Fields not displayed correctly when editing a simulation.

Outlined standard behavior: 
![image](https://github.com/user-attachments/assets/603625f7-4444-4d85-8daa-3b18556c520f)

Current behavior:
![image](https://github.com/user-attachments/assets/70ed62c8-eeeb-4829-9a37-47e8ab73f765)

**Comment by jborozco** [comment] 2024-10-14 07:12
Duplicate of https://github.com/OpenBAS-Platform/openbas/issues/1632

**Closed by jborozco** 2024-10-14 07:12 UTC
Labels: bug, needs triage
