### ISSUE TITLE
Restrictive grants are not working

### ISSUE THREAD

**Issue by jborozco** [OpenBAS-Platform/openbas#1960] opened 2024-11-29 15:26 UTC
## Description

- A client brought to us the fact that with a restrected user account, the platform is way slower. (Need to verify if the issue remains with our 1.9 release)
- When I tried to test, I created a user non-admin in a group with restricted rights but once I connect nothing is accessible at all (see screenshot).
![Image](https://github.com/user-attachments/assets/99cb99fc-662b-4f0e-b584-3c3cf61afaf9)
- I'm leaving the credential in the sidebar comment to test on https://testing.obas.staging.filigran.io/

**Comment by EllynBsc** [comment] 2024-12-02 15:35
Hi @jborozco 👋 

On this topic, we had something similar [here](https://github.com/OpenBAS-Platform/openbas/issues/1778) that was solved a few days ago (cc @MarineLeM )

I just tested and a non admin user in my group has access to a specific simulation/scenario granted on my side so it's working properly
![Image](https://github.com/user-attachments/assets/b4521c9a-0193-48bb-b36b-96a850cb464c)


But the platform is way slower indeed when i'm logged in as a non-admin user.

**Comment by savacano28** [comment] 2024-12-13 13:57
@jborozco @EllynBsc I’m logged into the platform, and it doesn't seem slower for me.
![Image](https://github.com/user-attachments/assets/a70f42be-7aec-4a2b-af44-310d6e14e431)
 ![Image](https://github.com/user-attachments/assets/3db0f0d3-3275-4984-b385-279c71fb2629)

Thanks!

**Comment by savacano28** [comment] 2024-12-14 09:05
@EllynBsc on testing :) (Jb credentials are for testing)

**Comment by RomuDeuxfois** [comment] 2024-12-19 08:57
Confirmation on the user side that the problem is no longer present.
We can close this ticket.

**Closed by RomuDeuxfois** 2024-12-19 08:57 UTC
Labels: bug, regression
