### ISSUE TITLE
MITRE ATT&CK matrix dashboard results is not working

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1670] opened 2024-10-17 13:12 UTC
## Description

1 simulation only:

![image](https://github.com/user-attachments/assets/b7333e32-1a5a-40e0-bd09-731757575ae0)

https://filigran.obas.filigran.io/admin/exercises/e8ff9a39-c2be-44a2-8061-fdb6669630c9

Result in dashboard (home):

![image](https://github.com/user-attachments/assets/5b26f617-5d6e-435a-82cc-eee1690b3278)

**Comment by EllynBsc** [comment] 2024-10-17 13:39
Duplicate of [971](https://github.com/OpenBAS-Platform/openbas/issues/970)

**Closed** 2024-10-17 16:09 UTC
Labels: bug
