### ISSUE TITLE
Be able to schedule injects based on the results / expectations of previous injects

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#202] opened 2022-10-10 08:04 UTC
## Problem to Solve

Be able to schedule injects based on the results / expectations of previous injects

Chunk of https://github.com/OpenBAS-Platform/openbas/issues/311

**Comment by EllynBsc** [comment] 2024-09-17 09:04
Duplicate of [#202](https://github.com/OpenBAS-Platform/openbas/issues/202)

**Closed by EllynBsc** 2024-09-17 09:04 UTC
Labels: feature
