### ISSUE TITLE
Top attack patterns in home dashboard is not working

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#1671] opened 2024-10-17 13:17 UTC
## Description

![image](https://github.com/user-attachments/assets/0b6f1b54-dd3c-4b77-8c5c-21a658969965)

**Comment by EllynBsc** [comment] 2024-10-17 13:43
Duplicate of [970](https://github.com/OpenBAS-Platform/openbas/issues/970)

**Closed** 2024-10-17 13:43 UTC
Labels: bug, duplicate
