### ISSUE TITLE
Execution details screen when there are multiple assets is unclear

### ISSUE THREAD

**Issue by RomuDeuxfois** [OpenBAS-Platform/openbas#1819] opened 2024-11-05 21:51 UTC
## Description

Create a technical injects with multiple assets (or asset groups).
Launch it.
When it's finished, go to the execution details tab.
We don't have the correspondence between assets and traces.

![image](https://github.com/user-attachments/assets/2b22678b-07bd-47c9-8665-98c9b5376e1c)
![image](https://github.com/user-attachments/assets/acdc4de7-4ffa-4fa1-8382-0cb4575ea37b)

https://testing.obas.staging.filigran.io/admin/exercises/a524e81c-9a44-4148-96c2-cc69242faa85/injects/44467323-356e-4a93-bcb6-6c5b49097b56?backlabel=Animation&backuri=/admin/exercises/a524e81c-9a44-4148-96c2-cc69242faa85/animation/timeline

**Comment by jborozco** [comment] 2024-11-06 08:16
I think the UI should be improved but do we have a quick win by showing which machine is impacted directly in the trace ?

**Comment by MarineLeM** [comment] 2024-11-06 11:05
Unfortunately, @jborozco , there’s no quick fix. The trace doesn’t include any information about the asset. When the implant finishes its task, it notifies the API using the injectId, but no asset details are provided.

**Comment by MarineLeM** [comment] 2024-11-15 13:23
@jborozco 
Moreover, The tracking of the total count data is unclear. It currently represents the number of executions **expected** per asset (including prerequisites, commands, and cleanup). However, the traces section below shows traces for all assets, creating confusion.

For instance, in my screenshot, there is one command and two assets, making the tracking total count 1, yet there are two traces—one per asset. This data is also provided even when no execution will occur.

![Image](https://github.com/user-attachments/assets/9020fa33-02bc-4ad0-b0c3-ce91fb998f36)


What exactly should this number represent? Expected executions per asset, for all assets, only those actually executed per asset, or all assets combined?

**Comment by EllynBsc** [comment] 2024-12-09 19:02
Duplicate of [#1951](https://github.com/OpenBAS-Platform/openbas/issues/1951)

**Closed by EllynBsc** 2024-12-09 19:02 UTC
Labels: duplicate, feature
