### ISSUE TITLE
Add more filters for simulation, atomic testings and scenarios

### ISSUE THREAD

**Issue by marckto-filigran** [OpenBAS-Platform/openbas#932] opened 2024-05-22 13:34 UTC
## Use case

Today, we can only filter on the name and tags, it would be good to have all the columns searchables

## Proposed Solution

All the columns can be added in the filter.

**Comment by Jipegien** [comment] 2024-05-22 16:36
duplicate of https://github.com/OpenBAS-Platform/openbas/issues/124

**Closed** 2024-05-22 16:38 UTC
Labels: duplicate
