### ISSUE TITLE
Extend IMAP capabilities to oauth / built-in APIs on O365 / Gmail

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/openbas#196] opened 2022-10-02 20:09 UTC
## Problem to Solve

Extend IMAP capabilities to oauth / built-in APIs on O365 / Gmail

**Comment by vletoux** [comment] 2023-09-19 13:46
see PR #289

**Comment by jborozco** [comment] 2024-05-21 10:38
Duplicate of #197

**Closed by jborozco** 2024-05-21 10:38 UTC
Labels: feature
