### ISSUE TITLE
[Inject] The "trigger now" function doesn't work

### ISSUE THREAD

**Issue by Lhorus6** [OpenBAS-Platform/openbas#887] opened 2024-05-15 22:07 UTC
## Description

When I try to "trigger now" an inject in a simulation, nothing happens

## Environment

OBAS 1.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation
2. Create an inject "send individual mail" and set the config that you want
3. In the list view of the inject (i.e. in the "inject" tab of the simulation), click on the burger menu at the end of the line of the inject created
4. Click on "trigger now"
-> Nothing happen

## Expected Output

I hope my inject launches

## Screenshots (optional)

![Screenshot 2024-05-16 000644](https://github.com/OpenBAS-Platform/openbas/assets/70956706/93f0ebdd-eb49-4982-8e9a-37158e2ab6e5)

**Comment by guillaumejparis** [comment] 2024-05-21 13:22
Duplicate of #897

**Closed by guillaumejparis** 2024-05-21 13:22 UTC
Labels: bug
