### ISSUE TITLE
Recurrence is not exported in scenario

### ISSUE THREAD

**Issue by guillaumejparis** [OpenBAS-Platform/openbas#1530] opened 2024-09-25 09:21 UTC
When exporting a scenario the scenario recurrence start, end & rhythm are not exported.

**Comment by jborozco** [comment] 2024-09-26 07:19
I think it was by design to avoid launching scenarios by mistake when you duplicate one

**Comment by RomuDeuxfois** [comment] 2024-09-30 13:11
I have the same feelings as JB.
We can close this issue if it's ok for everyone.

**Comment by jborozco** [comment] 2024-09-30 13:49
closing it for now

**Closed by jborozco** 2024-09-30 13:49 UTC
Labels: bug, wontfix
